apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-to-s3
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "valheim.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: "{{ .Values.cronJobs.updateCronOffset }}"  # Use the offset schedule from values.yaml
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aws-cli
            image: amazon/aws-cli
            command:
              - sh
              - -c #aws s3 sync s3://valheim-690090428495/valheim-data/ /mnt/ebs/valheim-server-config/
              - |
                aws s3 sync {{ .Values.persistence.config.configPath | default "/mnt/ebs/valheim-server-config/" }} s3://valheim-690090428495/valheim-data/
            env:
            - name: AWS_REGION
              value: "eu-north-1"
            volumeMounts:
            - name: ebs-storage
              mountPath: /mnt/ebs
          restartPolicy: OnFailure
          volumes:
          - name: ebs-storage
            hostPath:
              path: {{ .Values.persistence.config.configPath | default "/mnt/ebs/valheim-server-config/" }}
              type: DirectoryOrCreate
